<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import BottomNav from "@/components/BottomNav.vue";
import { deleteAccount, getSession, listProducts, logout, type Actor, type Product } from "@/services/api";

const actor=ref<Actor|null>(null);const products=ref<Product[]>([]);const loading=ref(true);const busy=ref(false);const message=ref("");const deletionOpen=ref(false);const confirmation=ref("");
const reminderCount=computed(()=>products.value.filter(item=>item.status==='active'&&item.schedule.reminderTimes.length).length);
async function refresh(){loading.value=true;message.value="";try{actor.value=await getSession();products.value=actor.value.kind==='registered'?await listProducts():[]}catch(error){message.value=error instanceof Error?error.message:"账户信息加载失败。"}finally{loading.value=false}}
onMounted(refresh);
function auth(){uni.navigateTo({url:"/pages/auth/index"})}function admin(){uni.navigateTo({url:"/pages/admin/invitations"})}function cabinet(){uni.reLaunch({url:"/pages/cabinet/index"})}
async function signOut(){busy.value=true;try{await logout();uni.reLaunch({url:"/pages/today/index"})}catch(error){message.value=error instanceof Error?error.message:"退出失败。"}finally{busy.value=false}}
async function remove(){if(!actor.value?.email)return;busy.value=true;message.value="";try{await deleteAccount(confirmation.value);uni.showToast({title:"删除任务已提交",icon:"success"});setTimeout(()=>uni.reLaunch({url:"/pages/today/index"}),700)}catch(error){message.value=error instanceof Error?error.message:"账户删除申请失败。"}finally{busy.value=false}}
</script>

<template><view class="page"><view class="bar"><view class="mark">Q</view><text>我的</text></view><main class="content"><view class="intro"><text class="title">我的</text><text class="subtitle">账户、提醒与隐私边界。</text></view><view v-if="message" class="error">{{message}}</view><view v-if="loading" class="card">正在读取账户…</view><template v-else-if="actor"><section class="card account"><view><text class="section-title">{{actor.kind==='registered'?actor.email:'独立演示访客'}}</text><text class="meta">{{actor.kind==='registered'?'数据保存在你的真实空间，可跨设备登录':'数据只属于当前演示空间，24 小时无活动后清理'}}</text></view><text class="badge">{{actor.role==='admin'?'管理员':actor.kind==='registered'?'已登录':'演示'}}</text></section><button v-if="actor.kind==='demo_ephemeral'" class="primary" @click="auth">登录或使用邀请注册</button><template v-else><section class="card"><text class="section-title">应用内提醒</text><text class="meta">{{reminderCount}} 个使用中的产品设置了提醒时间。V1 只在应用内汇总，不会发送 Web Push。</text><button class="row" @click="cabinet"><text>去产品详情调整时间</text><text>›</text></button></section><section v-if="actor.role==='admin'" class="card"><text class="section-title">管理</text><button class="row" @click="admin"><text>邀请管理</text><text>›</text></button></section><section class="card"><text class="section-title">隐私与数据</text><text class="meta">标签图片仅用于识别和人工确认；识别候选不会自动成为服用计划。外部 OCR / AI 处理目的和服务方应以正式上线隐私说明为准。</text><button class="row" :disabled="busy" @click="signOut"><text>退出当前设备</text><text>›</text></button></section><section class="card danger-zone"><text class="section-title">删除账户</text><text class="meta">提交后立即退出所有设备。后台先删除私有标签原图，再删除产品、记录、身份和账户数据；失败任务会自动重试。</text><button v-if="!deletionOpen" class="danger" @click="deletionOpen=true">永久删除账户</button><view v-else class="confirm"><label><text>输入账户邮箱以确认</text><input v-model.trim="confirmation" :placeholder="actor.email"/></label><view class="actions"><button class="secondary" @click="deletionOpen=false;confirmation=''">取消</button><button class="danger" :disabled="busy||confirmation!==actor.email" @click="remove">确认永久删除</button></view></view></section></template></template></main><BottomNav current="me"/></view></template>

<style lang="scss" scoped>
.page{min-height:100vh;padding-bottom:calc(116rpx + env(safe-area-inset-bottom));background:#f7f5f2;color:#292824}.bar{display:flex;align-items:center;gap:16rpx;padding:calc(22rpx + env(safe-area-inset-top)) 34rpx 20rpx;border-bottom:1rpx solid #e6e1d9;font-size:25rpx;font-weight:650}.mark{display:grid;place-items:center;width:48rpx;height:48rpx;border-radius:14rpx;background:#3f6a52;color:white}.content{width:min(100%,820rpx);margin:auto;padding:50rpx 34rpx 100rpx}.intro{display:flex;flex-direction:column;margin-bottom:34rpx}.title{font-family:Georgia,"Songti SC",serif;font-size:60rpx}.subtitle{margin-top:8rpx;color:#77736b;font-size:22rpx}.card,.error{display:flex;margin-bottom:20rpx;padding:28rpx;border:1rpx solid #e3ded6;border-radius:20rpx;background:#fffefa;flex-direction:column;gap:18rpx}.account{align-items:flex-start;justify-content:space-between;flex-direction:row}.account>view{display:flex;min-width:0;flex-direction:column;gap:7rpx}.section-title{font-size:25rpx;font-weight:650}.meta{color:#7d7870;font-size:19rpx;line-height:1.55}.badge{padding:8rpx 13rpx;border-radius:999rpx;background:#edf2ed;color:#4d6957;font-size:17rpx}.primary{width:100%;margin:0 0 20rpx;padding:22rpx;border-radius:14rpx;background:#47735a;color:#fffefa;font-size:22rpx}.row{display:flex;justify-content:space-between;width:100%;margin:0;padding:18rpx 0 0;border-top:1rpx solid #eee9e2;background:transparent;color:#4f4b44;font-size:21rpx;text-align:left}.row::after{display:none}.danger-zone{margin-top:38rpx;border-color:#e5cfc9}.danger{margin:0;padding:19rpx;border-radius:12rpx;background:#a65346;color:white;font-size:20rpx}.confirm{display:flex;flex-direction:column;gap:18rpx}.confirm label{display:flex;flex-direction:column;gap:9rpx;color:#706b63;font-size:18rpx}.confirm input{height:72rpx;padding:0 17rpx;border:1rpx solid #dec9c4;border-radius:11rpx;background:#fff;color:#292824;font-size:21rpx}.actions{display:grid;grid-template-columns:1fr 1fr;gap:12rpx}.secondary{margin:0;padding:19rpx;border:1rpx solid #ddd7cf;border-radius:12rpx;background:#fff;color:#5f5a52;font-size:20rpx}.error{border-color:#e4c3bc;background:#fbf1ef;color:#955446;font-size:20rpx}@media(min-width:780px){.page{padding-bottom:40px}}
</style>
