<script setup lang="ts">
import { onMounted, ref } from "vue";
import { listProducts, type Product } from "@/services/api";
import BottomNav from "@/components/BottomNav.vue";
const products=ref<Product[]>([]);const loading=ref(true);const message=ref("");
async function refresh(){loading.value=true;try{products.value=await listProducts()}catch(error){message.value=error instanceof Error?error.message:"补充柜加载失败。"}finally{loading.value=false}}
onMounted(refresh);
function back(){uni.navigateBack()}
function add(){uni.navigateTo({url:"/pages/product/add"})}
function open(product:Product){uni.navigateTo({url:`/pages/product/detail?id=${encodeURIComponent(product.id)}`})}
</script>
<template><view class="page"><view class="bar"><button class="plain" @click="back">‹ 今日</button><text class="bar-title">补充柜</text><button class="plain accent" @click="add">添加</button></view><main class="content"><view class="intro"><text class="title">补充柜</text><text class="subtitle">库存以批次余额为唯一真相；点击产品可补货或改计划。</text></view><view v-if="message" class="error">{{message}}</view><view v-if="loading" class="empty">正在读取库存…</view><view v-else-if="products.length===0" class="empty"><text class="empty-title">还没有产品</text><text>添加第一件补剂后，计划才会出现在“今天”。</text><button class="primary" @click="add">添加产品</button></view><section v-for="product in products" :key="product.id" class="product-card" @click="open(product)"><view class="product-head"><view class="copy"><text class="name">{{product.name}}</text><text class="meta">{{product.brand||"未填写品牌"}} · 每日 {{product.dailyQuantity}} {{product.unit}}</text></view><view class="quantity"><text class="number">{{product.currentQuantity}}</text><text>{{product.unit}} ›</text></view></view><view class="risk" :class="`risk--${product.expiryRisk.level}`"><text>{{product.expiryRisk.message}}</text><text v-if="product.expiryRisk.expiryDate">有效期 {{product.expiryRisk.expiryDate}}</text></view><view class="batch-title">批次</view><view v-for="batch in product.batches" :key="batch.id" class="batch"><text>{{batch.currentQuantity}} / {{batch.initialQuantity}} {{product.unit}}</text><text>{{batch.expiryDate?`至 ${batch.expiryDate}`:"未设置有效期"}}</text></view></section></main><BottomNav current="cabinet" /></view></template>
<style lang="scss" scoped>.page{min-height:100vh;padding-bottom:calc(116rpx + env(safe-area-inset-bottom));background:#f7f5f2;color:#292824}.bar{position:sticky;top:0;z-index:2;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:calc(18rpx + env(safe-area-inset-top)) 28rpx 18rpx;border-bottom:1rpx solid #e6e1d9;background:rgba(247,245,242,.94);backdrop-filter:blur(16px)}.bar-title{text-align:center;font-size:26rpx;font-weight:650}.plain{margin:0;padding:8rpx 0;background:transparent;color:#77736b;font-size:22rpx;line-height:1.4;text-align:left}.plain::after{display:none}.plain:last-child{text-align:right}.accent{color:#3f6a52;font-weight:650}.content{width:min(100%,900rpx);margin:auto;padding:48rpx 34rpx 90rpx}.intro{display:flex;flex-direction:column;margin-bottom:40rpx}.title{font-family:Georgia,"Songti SC",serif;font-size:60rpx}.subtitle{margin-top:8rpx;color:#77736b;font-size:23rpx}.product-card,.empty,.error{margin-bottom:20rpx;padding:30rpx;border:1rpx solid #e3ded6;border-radius:22rpx;background:#fffefa}.product-card{cursor:pointer}.product-head{display:flex;align-items:flex-start;gap:20rpx}.copy{display:flex;flex:1;flex-direction:column;gap:8rpx}.name{font-size:29rpx;font-weight:650}.meta{color:#858078;font-size:20rpx}.quantity{display:flex;align-items:baseline;gap:5rpx;color:#4d6957;font-size:19rpx}.number{font-family:Georgia,serif;font-size:40rpx}.risk{display:flex;justify-content:space-between;margin:24rpx 0;padding:16rpx 18rpx;border-radius:12rpx;background:#f2f1ed;color:#6f6a62;font-size:18rpx}.risk--warn{background:#f5efe2;color:#856737}.risk--danger{background:#f8eae6;color:#9a4e3b}.batch-title{margin-bottom:10rpx;color:#7e7971;font-size:18rpx;text-transform:uppercase}.batch{display:flex;justify-content:space-between;padding:14rpx 0;border-top:1rpx solid #eeeae4;color:#68635c;font-size:20rpx}.empty{display:flex;align-items:flex-start;flex-direction:column;gap:12rpx;color:#7e7971;font-size:21rpx}.empty-title{color:#35332f;font-size:28rpx;font-weight:650}.primary{margin:20rpx 0 0;padding:18rpx 28rpx;border-radius:14rpx;background:#47735a;color:#fffefa;font-size:22rpx}.error{border-color:#e4c3bc;background:#fbf1ef;color:#955446;font-size:21rpx}@media(min-width:780px){.page{padding-bottom:40px}}</style>
