<script setup lang="ts">
import { reactive, ref } from "vue";
import { createProduct } from "@/services/api";
const now=new Date();const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`;
const weekdays=[{v:1,l:"一"},{v:2,l:"二"},{v:3,l:"三"},{v:4,l:"四"},{v:5,l:"五"},{v:6,l:"六"},{v:0,l:"日"}];
const form=reactive({name:"",brand:"",unit:"粒",doseQuantity:1,doseTimesPerDay:1,quantity:30,expiryDate:"",priceCny:0,reminderTime:"09:00",startDate:today,selectedWeekdays:[0,1,2,3,4,5,6] as number[],dayEnabled:false,cycleDays:28,takeDays:21,longEnabled:false,takeWeeks:6,restWeeks:4,ingredientName:"",ingredientAmount:0,ingredientUnit:"mg"});
const saving=ref(false);const message=ref("");
function back(){uni.navigateBack()}
function toggleWeekday(value:number){const index=form.selectedWeekdays.indexOf(value);if(index>=0)form.selectedWeekdays.splice(index,1);else form.selectedWeekdays.push(value)}
function switchValue(event:Event){return (event as Event&{detail:{value:boolean}}).detail.value}
function setDayEnabled(event:Event){form.dayEnabled=switchValue(event)}
function setLongEnabled(event:Event){form.longEnabled=switchValue(event)}
async function submit(){message.value="";if(!form.name.trim()){message.value="请填写产品名称。";return}if(form.selectedWeekdays.length===0){message.value="至少选择一个星期。";return}saving.value=true;try{await createProduct({name:form.name,brand:form.brand,productType:"supplement",unit:form.unit,doseQuantity:Number(form.doseQuantity),doseTimesPerDay:Number(form.doseTimesPerDay),ingredientServingQuantity:Number(form.doseQuantity),restockThresholdDays:7,expiryReminderDays:30,schedule:{startDate:form.startDate,weekdays:form.selectedWeekdays,dayCycle:{enabled:form.dayEnabled,cycleDays:Number(form.cycleDays),takeDays:Number(form.takeDays),anchorDate:form.startDate},longCycle:{enabled:form.longEnabled,takeWeeks:Number(form.takeWeeks),restWeeks:Number(form.restWeeks),startDate:form.startDate},reminderTimes:[form.reminderTime]},openingBatch:{quantity:Number(form.quantity),expiryDate:form.expiryDate,priceCny:Number(form.priceCny)},ingredients:form.ingredientName.trim()?[{key:form.ingredientName,name:form.ingredientName,amount:Number(form.ingredientAmount),unit:form.ingredientUnit}]:[]});uni.showToast({title:"已加入补充柜",icon:"success"});setTimeout(()=>uni.reLaunch({url:"/pages/today/index"}),500)}catch(error){message.value=error instanceof Error?error.message:"保存失败。"}finally{saving.value=false}}
</script>
<template><view class="page"><view class="bar"><button class="plain" @click="back">取消</button><text class="bar-title">添加产品</text><view/></view><main class="content"><view class="intro"><text class="title">新产品</text><text class="subtitle">首批库存和计划一起建立，之后每次入库都保留独立批次。</text></view><view v-if="message" class="error">{{message}}</view><section class="card"><text class="section-title">基本信息</text><label><text>产品名称</text><input v-model="form.name" placeholder="例如：维生素 D3"/></label><label><text>品牌</text><input v-model="form.brand" placeholder="可选"/></label><view class="grid"><label><text>库存单位</text><input v-model="form.unit"/></label><label><text>每次用量</text><input v-model="form.doseQuantity" type="digit"/></label><label><text>每日次数</text><input v-model="form.doseTimesPerDay" type="number"/></label></view></section><section class="card"><text class="section-title">首批库存</text><view class="grid"><label><text>数量</text><input v-model="form.quantity" type="digit"/></label><label><text>价格（元）</text><input v-model="form.priceCny" type="digit"/></label></view><label><text>有效期</text><input v-model="form.expiryDate" placeholder="YYYY-MM-DD，可选"/></label></section><section class="card"><text class="section-title">每周计划</text><label><text>开始日期</text><input v-model="form.startDate"/></label><view class="weekday-row"><button v-for="day in weekdays" :key="day.v" class="weekday" :class="{'weekday--active':form.selectedWeekdays.includes(day.v)}" @click="toggleWeekday(day.v)">{{day.l}}</button></view><label><text>提醒时间</text><input v-model="form.reminderTime"/></label></section><section class="card"><view class="switch-row"><view><text class="section-title">日周期</text><text class="hint">例如吃 21 天、停 7 天</text></view><switch :checked="form.dayEnabled" color="#47735a" @change="setDayEnabled"/></view><view v-if="form.dayEnabled" class="grid"><label><text>完整周期（天）</text><input v-model="form.cycleDays" type="number"/></label><label><text>服用天数</text><input v-model="form.takeDays" type="number"/></label></view><view class="switch-row divided"><view><text class="section-title">长周期</text><text class="hint">例如吃 6 周、停 4 周</text></view><switch :checked="form.longEnabled" color="#47735a" @change="setLongEnabled"/></view><view v-if="form.longEnabled" class="grid"><label><text>服用周数</text><input v-model="form.takeWeeks" type="number"/></label><label><text>停用周数</text><input v-model="form.restWeeks" type="number"/></label></view></section><section class="card"><text class="section-title">主要成分（可选）</text><label><text>成分名</text><input v-model="form.ingredientName" placeholder="例如：镁"/></label><view class="grid"><label><text>含量</text><input v-model="form.ingredientAmount" type="digit"/></label><label><text>单位</text><input v-model="form.ingredientUnit"/></label></view></section><button class="submit" :disabled="saving" @click="submit">{{saving?"正在保存…":"保存并开始计划"}}</button></main></view></template>
<style lang="scss" scoped>.page{min-height:100vh;background:#f7f5f2;color:#292824}.bar{position:sticky;top:0;z-index:2;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:calc(18rpx + env(safe-area-inset-top)) 28rpx 18rpx;border-bottom:1rpx solid #e6e1d9;background:rgba(247,245,242,.94);backdrop-filter:blur(16px)}.bar-title{font-size:26rpx;font-weight:650}.plain{margin:0;padding:8rpx 0;background:transparent;color:#77736b;font-size:22rpx;text-align:left}.plain::after{display:none}.content{width:min(100%,860rpx);margin:auto;padding:48rpx 34rpx 100rpx}.intro{display:flex;flex-direction:column;margin-bottom:34rpx}.title{font-family:Georgia,"Songti SC",serif;font-size:56rpx}.subtitle{margin-top:10rpx;color:#77736b;font-size:22rpx;line-height:1.5}.card{display:flex;flex-direction:column;gap:24rpx;margin-bottom:20rpx;padding:30rpx;border:1rpx solid #e3ded6;border-radius:22rpx;background:#fffefa}.section-title{font-size:25rpx;font-weight:650}.card label{display:flex;flex-direction:column;gap:10rpx;color:#77736b;font-size:19rpx}.card input{box-sizing:border-box;height:74rpx;padding:0 18rpx;border:1rpx solid #ded9d1;border-radius:12rpx;background:#faf9f6;color:#292824;font-size:23rpx}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18rpx}.grid label:last-child:nth-child(3){grid-column:span 2}.weekday-row{display:flex;justify-content:space-between;gap:8rpx}.weekday{display:grid;place-items:center;width:60rpx;height:60rpx;margin:0;padding:0;border:1rpx solid #ded9d1;border-radius:50%;background:#faf9f6;color:#716c64;font-size:20rpx;line-height:1}.weekday::after{display:none}.weekday--active{border-color:#47735a;background:#47735a;color:white}.switch-row{display:flex;align-items:center;justify-content:space-between}.switch-row>view{display:flex;flex-direction:column;gap:5rpx}.hint{color:#8b867d;font-size:18rpx}.divided{margin-top:8rpx;padding-top:26rpx;border-top:1rpx solid #eee9e2}.submit{margin-top:14rpx;padding:24rpx;border-radius:18rpx;background:#47735a;color:#fffefa;font-size:25rpx;font-weight:650}.submit[disabled]{opacity:.55}.error{margin-bottom:20rpx;padding:22rpx 26rpx;border:1rpx solid #e4c3bc;border-radius:18rpx;background:#fbf1ef;color:#955446;font-size:21rpx}</style>
