<script setup lang="ts">
import { computed, reactive, ref } from "vue";
import { onLoad } from "@dcloudio/uni-app";
import { addBatch, getProduct, updateProduct, type Product, type UpdateProductInput } from "@/services/api";

const product = ref<Product | null>(null);
const productId = ref("");
const loading = ref(true);
const saving = ref(false);
const message = ref("");
const success = ref("");
const showRestock = ref(false);
const weekdays=[{v:1,l:"一"},{v:2,l:"二"},{v:3,l:"三"},{v:4,l:"四"},{v:5,l:"五"},{v:6,l:"六"},{v:0,l:"日"}];
const form=reactive({name:"",brand:"",unit:"粒",doseQuantity:1,doseTimesPerDay:1,restockThresholdDays:7,expiryReminderDays:30,status:"active" as Product["status"],startDate:"",weekdays:[] as number[],reminderTime:"09:00",dayEnabled:false,cycleDays:28,takeDays:28,dayAnchor:"",longEnabled:false,takeWeeks:6,restWeeks:4,longStart:""});
const batch=reactive({quantity:30,expiryDate:"",priceCny:0});
const canSave=computed(()=>Boolean(form.name.trim()&&form.unit.trim()&&Number(form.doseQuantity)>0&&Number(form.doseTimesPerDay)>0&&form.weekdays.length));

function apply(value:Product){
  product.value=value;form.name=value.name;form.brand=value.brand;form.unit=value.unit;form.doseQuantity=value.doseQuantity;form.doseTimesPerDay=value.doseTimesPerDay;form.restockThresholdDays=value.restockThresholdDays;form.expiryReminderDays=value.expiryReminderDays;form.status=value.status;form.startDate=value.schedule.startDate;form.weekdays=[...value.schedule.weekdays];form.reminderTime=value.schedule.reminderTimes[0]||"09:00";form.dayEnabled=value.schedule.dayCycle.enabled;form.cycleDays=value.schedule.dayCycle.cycleDays;form.takeDays=value.schedule.dayCycle.takeDays;form.dayAnchor=value.schedule.dayCycle.anchorDate;form.longEnabled=value.schedule.longCycle.enabled;form.takeWeeks=value.schedule.longCycle.takeWeeks;form.restWeeks=value.schedule.longCycle.restWeeks;form.longStart=value.schedule.longCycle.startDate;
}
async function load(){loading.value=true;message.value="";try{apply(await getProduct(productId.value))}catch(error){message.value=error instanceof Error?error.message:"产品加载失败。"}finally{loading.value=false}}
onLoad((query)=>{productId.value=String(query?.id||"");if(!productId.value){message.value="缺少产品编号。";loading.value=false;return}void load()});
function back(){uni.navigateBack()}
function toggleWeekday(value:number){const index=form.weekdays.indexOf(value);if(index>=0)form.weekdays.splice(index,1);else form.weekdays.push(value)}
function switchValue(event:Event){return (event as Event&{detail:{value:boolean}}).detail.value}
function todayKey(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`}
async function save(){
  if(!product.value||!canSave.value)return;saving.value=true;message.value="";success.value="";
  const input:UpdateProductInput={name:form.name.trim(),brand:form.brand.trim(),productType:product.value.productType,status:form.status,unit:form.unit.trim(),doseQuantity:Number(form.doseQuantity),doseTimesPerDay:Number(form.doseTimesPerDay),ingredientServingQuantity:product.value.ingredientServingQuantity||Number(form.doseQuantity),withFood:product.value.withFood,restockThresholdDays:Number(form.restockThresholdDays),expiryReminderDays:Number(form.expiryReminderDays),schedule:{startDate:form.startDate,weekdays:[...form.weekdays].sort(),dayCycle:{enabled:form.dayEnabled,cycleDays:Number(form.cycleDays),takeDays:Number(form.takeDays),anchorDate:form.dayAnchor||form.startDate},longCycle:{enabled:form.longEnabled,takeWeeks:Number(form.takeWeeks),restWeeks:Number(form.restWeeks),startDate:form.longStart||form.startDate},reminderTimes:[form.reminderTime]},ingredients:product.value.ingredients.map(item=>({key:item.key,name:item.name,amount:item.amount,unit:item.unit})),effectiveDate:todayKey()};
  try{apply(await updateProduct(productId.value,input));success.value="产品与计划已保存，新日周期从今天起生效。"}catch(error){message.value=error instanceof Error?error.message:"保存失败。"}finally{saving.value=false}
}
async function restock(){saving.value=true;message.value="";success.value="";try{apply(await addBatch(productId.value,{quantity:Number(batch.quantity),expiryDate:batch.expiryDate||undefined,priceCny:Number(batch.priceCny)}));showRestock.value=false;success.value="补货已入库，风险与可用天数已重新计算。"}catch(error){message.value=error instanceof Error?error.message:"补货失败。"}finally{saving.value=false}}
</script>

<template>
  <view class="page"><view class="bar"><button class="plain" @click="back">‹ 补充柜</button><text class="bar-title">产品详情</text><button class="plain accent" :disabled="saving||!canSave" @click="save">保存</button></view>
    <main class="content"><view v-if="message" class="error">{{message}}</view><view v-if="success" class="success">{{success}}</view><view v-if="loading" class="empty">正在读取产品…</view>
      <template v-else-if="product">
        <view class="intro"><view><text class="title">{{product.name}}</text><text class="subtitle">计划版本 {{product.schedule.version}} · 当前 {{product.currentQuantity}} {{product.unit}}</text></view><button class="restock" @click="showRestock=!showRestock">{{showRestock?'取消':'补货'}}</button></view>
        <section v-if="showRestock" class="card restock-card"><text class="section-title">新增库存批次</text><view class="grid"><label><text>数量</text><input v-model="batch.quantity" type="digit"/></label><label><text>价格（元）</text><input v-model="batch.priceCny" type="digit"/></label></view><label><text>有效期</text><input v-model="batch.expiryDate" placeholder="YYYY-MM-DD，可选"/></label><button class="primary" :disabled="saving||Number(batch.quantity)<=0" @click="restock">确认入库</button></section>
        <section class="card"><text class="section-title">基本信息</text><label><text>产品名称</text><input v-model.trim="form.name" maxlength="160"/></label><label><text>品牌</text><input v-model.trim="form.brand" maxlength="120"/></label><view class="grid"><label><text>库存单位</text><input v-model.trim="form.unit" maxlength="40"/></label><label><text>每次用量</text><input v-model="form.doseQuantity" type="digit"/></label><label><text>每日次数</text><input v-model="form.doseTimesPerDay" type="number"/></label></view><view class="switch-row"><view><text>暂停计划</text><text class="hint">暂停后不出现在“今天”</text></view><switch color="#47735a" :checked="form.status==='paused'" :disabled="product.currentQuantity===0" @change="form.status=switchValue($event)?'paused':'active'"/></view></section>
        <section class="card"><text class="section-title">服用计划</text><label><text>开始日期</text><input v-model="form.startDate" placeholder="YYYY-MM-DD"/></label><view class="weekday-row"><button v-for="day in weekdays" :key="day.v" :class="['weekday',{'weekday--active':form.weekdays.includes(day.v)}]" @click="toggleWeekday(day.v)">{{day.l}}</button></view><label><text>计划时点</text><input v-model="form.reminderTime" placeholder="09:00"/></label><text class="hint">用于生成今日任务，不代表已开启站内或系统通知。</text><view class="switch-row divided"><view><text>启用日周期</text><text class="hint">例如 28 天中服 21 天</text></view><switch color="#47735a" :checked="form.dayEnabled" @change="form.dayEnabled=switchValue($event)"/></view><view v-if="form.dayEnabled" class="grid"><label><text>周期天数</text><input v-model="form.cycleDays" type="number"/></label><label><text>服用天数</text><input v-model="form.takeDays" type="number"/></label><label><text>当前锚点</text><input v-model="form.dayAnchor"/></label></view><view class="switch-row divided"><view><text>启用服/停长周期</text><text class="hint">按连续周滚动</text></view><switch color="#47735a" :checked="form.longEnabled" @change="form.longEnabled=switchValue($event)"/></view><view v-if="form.longEnabled" class="grid"><label><text>服用周数</text><input v-model="form.takeWeeks" type="number"/></label><label><text>停用周数</text><input v-model="form.restWeeks" type="number"/></label><label><text>开始日期</text><input v-model="form.longStart"/></label></view></section>
        <section class="card"><text class="section-title">风险阈值</text><view class="grid"><label><text>提前补货（天）</text><input v-model="form.restockThresholdDays" type="number"/></label><label><text>有效期提醒（天）</text><input v-model="form.expiryReminderDays" type="number"/></label></view><view :class="['risk',`risk--${product.expiryRisk.level}`]"><text>{{product.expiryRisk.message}}</text><text v-if="product.expiryRisk.projectedFinishDate">预计用完 {{product.expiryRisk.projectedFinishDate}}</text></view></section>
        <section class="card"><text class="section-title">库存批次</text><view v-for="item in product.batches" :key="item.id" class="batch"><text>{{item.currentQuantity}} / {{item.initialQuantity}} {{product.unit}}</text><text>{{item.expiryDate||'无有效期'}}</text></view></section>
      </template>
    </main>
  </view>
</template>

<style lang="scss" scoped>
.page{min-height:100vh;background:#f7f5f2;color:#292824}.bar{position:sticky;top:0;z-index:2;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:calc(18rpx + env(safe-area-inset-top)) 28rpx 18rpx;border-bottom:1rpx solid #e6e1d9;background:rgba(247,245,242,.95);backdrop-filter:blur(16px)}.bar-title{text-align:center;font-size:25rpx;font-weight:650}.plain{margin:0;padding:8rpx 0;background:transparent;color:#77736b;font-size:21rpx;text-align:left}.plain::after{display:none}.plain:last-child{text-align:right}.accent{color:#3f6a52;font-weight:650}.content{width:min(100%,860rpx);margin:auto;padding:42rpx 34rpx 100rpx}.intro{display:flex;align-items:flex-start;justify-content:space-between;gap:20rpx;margin-bottom:30rpx}.intro>view{display:flex;min-width:0;flex-direction:column}.title{font-family:Georgia,"Songti SC",serif;font-size:50rpx}.subtitle{margin-top:8rpx;color:#7e7971;font-size:20rpx}.restock{margin:0;padding:14rpx 20rpx;border-radius:12rpx;background:#e8efe9;color:#3f6a52;font-size:20rpx}.card,.empty,.error,.success{display:flex;margin-bottom:20rpx;padding:28rpx;border:1rpx solid #e3ded6;border-radius:20rpx;background:#fffefa;flex-direction:column;gap:22rpx}.section-title{font-size:25rpx;font-weight:650}.card label{display:flex;flex-direction:column;gap:9rpx;color:#77736b;font-size:19rpx}.card input{height:72rpx;padding:0 17rpx;border:1rpx solid #ded9d1;border-radius:11rpx;background:#faf9f6;color:#292824;font-size:22rpx}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16rpx}.grid label:last-child:nth-child(3){grid-column:span 2}.weekday-row{display:flex;justify-content:space-between;gap:7rpx}.weekday{display:grid;place-items:center;width:58rpx;height:58rpx;margin:0;padding:0;border:1rpx solid #ded9d1;border-radius:50%;background:#faf9f6;color:#716c64;font-size:19rpx}.weekday::after{display:none}.weekday--active{border-color:#47735a;background:#47735a;color:white}.switch-row{display:flex;align-items:center;justify-content:space-between}.switch-row>view{display:flex;flex-direction:column;gap:4rpx}.hint{color:#8b867d;font-size:17rpx}.divided{padding-top:22rpx;border-top:1rpx solid #eee9e2}.primary{margin:0;padding:21rpx;border-radius:13rpx;background:#47735a;color:white;font-size:22rpx}.risk{display:flex;flex-direction:column;gap:5rpx;padding:16rpx;border-radius:11rpx;background:#f1f0ec;color:#6f6a62;font-size:18rpx}.risk--warn{background:#f5efe2;color:#856737}.risk--danger{background:#f8eae6;color:#9a4e3b}.batch{display:flex;justify-content:space-between;padding:13rpx 0;border-top:1rpx solid #eeeae4;color:#68635c;font-size:19rpx}.error{border-color:#e4c3bc;background:#fbf1ef;color:#955446;font-size:20rpx}.success{border-color:#cbdacb;background:#eef4ee;color:#42634d;font-size:20rpx}.empty{color:#7e7971;font-size:20rpx}
</style>
